<?php

const PASATIEMPO = "PASATIEMPO";
const PAS_ID = "PAS_ID";
const PAS_NOMBRE = "PAS_NOMBRE";
const PAS_DESCRIPCION = "PAS_DESCRIPCION";
const PAS_CATEGORIA = "PAS_CATEGORIA";
const PAS_DIFICULTAD = "PAS_DIFICULTAD";
const PAS_FECHA_CREACION = "PAS_FECHA_CREACION";
